#!/usr/bin/env python3
"""Genere un plan de 8 s puis l'etend de 8 s, pour un plan continu de 16 s.

    .venv/Scripts/python.exe chain.py <prefixe_de_sortie>

L'extension n'accepte QUE l'URI d'une video que Veo vient de produire :
  "Input video must be a video that was generated by VEO that has been processed."
Un fichier telecharge puis redepose est refuse, meme s'il venait de Veo.
Il faut donc enchainer dans la meme session, avant l'expiration (2 jours).

Contraintes constatees, non documentees :
  - modele : lite ne sait pas etendre, il faut fast ou la version pleine
  - person_generation : allow_all (allow_adult est refuse en extension)
  - video : ni `mime_type` (-> encoding), ni octets (-> encodedVideo). URI seulement.
  - resolution : 720p obligatoire. Une base en 1080p est refusee a l'extension.
"""
import os
import pathlib
import sys

from google import genai
from google.genai import types

import generate

MODEL = "veo-3.1-fast-generate-preview"
PRIX = 0.10   # 720p ; le 1080p est inextensible

STYLE = (
    "Cinematic, 35mm anamorphic, shallow depth of field, thick atmospheric haze, high "
    "contrast, desaturated steel-blue base with toxic green and violet practical lights, "
    "fine film grain, handheld with slow drift. "
    "No on-screen text, no subtitles, no captions, no watermark."
)

BASE = (
    "A Black man in his 30s with short twisted locs, a wooden bead necklace with a small "
    "cross and a black tactical vest, stands in a dark hall hung with heavy broken chains, "
    "tropical foliage crowding both edges of frame, violet and white smoke rolling past "
    "him. He raps hard straight to camera, jabbing his index finger at the lens. Slow "
    "push in from a medium shot. " + STYLE
)

SUITE = (
    "The shot continues without a cut. He keeps rapping straight to camera, breathing hard "
    "between lines. The broken chains behind him swing wider and fall away one by one into "
    "the smoke. The foliage closes in from both edges until it frames his face. The camera "
    "pushes slowly closer until his face fills the frame, then holds. " + STYLE
)


def config():
    return types.GenerateVideosConfig(
        aspect_ratio="16:9",
        resolution="720p",   # l'extension EXIGE du 720p en entree
        duration_seconds="8",
        person_generation="allow_all",
    )


def attendre(client, op, nom):
    op = generate.poll(client, op, nom, 900)
    vids = generate.videos_of(op)
    if not vids:
        sys.exit("%s refuse : %s" % (nom, generate.refusal_reason(op) or "motif non renvoye"))
    return vids[0].video


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    prefixe = pathlib.Path(sys.argv[1])
    prefixe.parent.mkdir(parents=True, exist_ok=True)

    generate.load_env()
    if not (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
        sys.exit("GEMINI_API_KEY absente.")

    print("%s, 2 x 8 s -> %.2f USD" % (MODEL, 16 * PRIX))
    client = genai.Client()

    print("[1/2] generation du plan de base...")
    op = client.models.generate_videos(
        model=MODEL,
        source=types.GenerateVideosSource(prompt=BASE),
        config=config(),
    )
    v1 = attendre(client, op, "base")
    uri = getattr(v1, "uri", None)
    if not uri:
        sys.exit("la generation n'a pas renvoye d'URI : extension impossible")
    print("      URI : %s" % uri)
    a = prefixe.with_name(prefixe.name + "_a.mp4")
    client.files.download(file=v1, destination=str(a))
    print("      -> %s" % a.name)

    print("[2/2] extension de 8 s depuis l'URI...")
    op = client.models.generate_videos(
        model=MODEL,
        source=types.GenerateVideosSource(prompt=SUITE, video=types.Video(uri=uri)),
        config=config(),
    )
    v2 = attendre(client, op, "extension")
    b = prefixe.with_name(prefixe.name + "_b.mp4")
    client.files.download(file=v2, destination=str(b))
    print("      -> %s" % b.name)
    print("\nOK. Assembler avec le demuxeur concat pour obtenir le plan continu.")


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    main()
